name: Create EC2 Instance with Terraform

on:
  push:
    branches:
      - main  

jobs:
  # Job 1: Create AMI
  create-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
        
- name: Sync system time
  run: sudo apt-get install ntpdate && sudo ntpdate time.nist.gov

      
      - name: Set up AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1  # Update to your region
        run: |
          echo "Setting up AWS CRedentials"
          
      - name: Set up Terraform
        uses: hashicorp/setup-
